version: "3"
services:
  python:
    build: ./app
    container_name: Lighthouse
    stdin_open: true
    tty: true
    environment:
      - checkInterval
      - twitchUrl
      - youTubeUrl
      - instaUrl
      - instaUsername
      - instaPassword
      - streamerName
      - redditClientId
      - redditClientSecret
      - redditUsername
      - redditPassword
      - redditSub
      - twitterApiKey
      - twitterSecretKey
      - twitterBearerToken
      - twitterAccessToken
      - twitterAccessTokenSecret
      - fbGroup
      - facebookUsername
      - facebookPassword
    depends_on: 
      - hub
      - redis
  
  redis: 
    image: "redis:alpine"
    volumes:
      - ./redis:/data

  hub:
    image: selenium/hub:latest
    environment:
      GRID_MAX_SESSION: 3
    ports:
      - 4444:4444
    networks:
      - selenium-grid
      - default

  chrome:
    image: selenium/node-chrome:latest
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - NODE_PORT=5555
    networks:
      - selenium-grid  
    depends_on:
      - hub

  firefox:
    image: selenium/node-firefox:latest
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - JAVA_OPTS=-Dwebdriver.firefox.whitelistedIps=
      - NODE_PORT=5556
    networks:
      - selenium-grid  
    depends_on:
      - hub

networks:
  selenium-grid:
    driver: bridge

